# Generated by Django 5.0.1 on 2024-01-19 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracker_app', '0002_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='label',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='label', to='time_tracker_app.label'),
            preserve_default=False,
        ),
    ]
